{
	"version": 1539766386,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/player-sheet0.png",
		"images/tiledbackground.png",
		"images/bullet-sheet0.png",
		"images/asteroid1-sheet0.png",
		"images/regioncounterclockwise-sheet0.png",
		"images/questionmark2b-sheet0.png",
		"images/spawner-sheet0.png",
		"images/calculator-sheet0.png",
		"images/regionasteroidcloseby-sheet0.png",
		"images/explosion-sheet0.png",
		"images/coverstartscreen.png",
		"media/shoot.ogg",
		"media/explosion 11.ogg",
		"media/space level 1.ogg",
		"media/space game over.ogg",
		"media/level up 4.ogg",
		"media/asteroid aproaching.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"pathfind.js"
	]
}